import type { ComponentType } from 'react';
import {
  Banknote,
  BookOpen,
  Briefcase,
  Calendar,
  Camera,
  Coffee,
  CreditCard,
  DollarSign,
  Download,
  FileText,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Headphones,
  Heart,
  JapaneseYen,
  Link as LinkIcon,
  Mail,
  MapPin,
  MessageCircle,
  Mic,
  Music,
  Newspaper,
  Phone,
  QrCode,
  Send,
  ShoppingBag,
  Star,
  Video,
} from 'lucide-react';
import {
  siApplemusic,
  siApplepodcasts,
  siArtstation,
  siBandcamp,
  siBehance,
  siBitcoin,
  siBluesky,
  siBuymeacoffee,
  siCalendly,
  siCashapp,
  siDevdotto,
  siDiscord,
  siDribbble,
  siEthereum,
  siEtsy,
  siFacebook,
  siFigma,
  siFlickr,
  siGithub,
  siGitlab,
  siGmail,
  siGoodreads,
  siGooglecalendar,
  siGooglemaps,
  siHashnode,
  siInstagram,
  siKick,
  siKofi,
  siLine,
  siLinktree,
  siMastodon,
  siMedium,
  siMessenger,
  siNotion,
  siPatreon,
  siPaypal,
  siPinterest,
  siPlaystation,
  siProducthunt,
  siReddit,
  siRevolut,
  siRoblox,
  siRumble,
  siShopify,
  siSignal,
  siSnapchat,
  siSoundcloud,
  siSpotify,
  siStackoverflow,
  siSteam,
  siStripe,
  siSubstack,
  siTelegram,
  siThreads,
  siTiktok,
  siTwitch,
  siUnsplash,
  siVenmo,
  siViber,
  siVimeo,
  siVk,
  siWechat,
  siWhatsapp,
  siWise,
  siX,
  siYoutube,
} from 'simple-icons';

// Generic icons (lucide). Name → component.
export const lucideIcons: Record<string, ComponentType<{ size?: number }>> = {
  link: LinkIcon,
  website: Globe,
  mail: Mail,
  phone: Phone,
  message: MessageCircle,
  send: Send,
  calendar: Calendar,
  location: MapPin,
  shop: ShoppingBag,
  card: CreditCard,
  khqr: QrCode,
  dollar: DollarSign,
  cny: JapaneseYen,
  khr: Banknote,
  resume: FileText,
  news: Newspaper,
  photos: Camera,
  video: Video,
  music: Music,
  mic: Mic,
  headphones: Headphones,
  game: Gamepad2,
  book: BookOpen,
  coffee: Coffee,
  gift: Gift,
  heart: Heart,
  star: Star,
  portfolio: Briefcase,
  download: Download,
  education: GraduationCap,
};

// LinkedIn was removed from simple-icons (brand policy), so its path is inlined.
const linkedinPath =
  'M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.225 0z';

// Brand icons (simple-icons). Name → SVG path string.
export const brandIcons: Record<string, string> = {
  instagram: siInstagram.path,
  facebook: siFacebook.path,
  x: siX.path,
  twitter: siX.path,
  threads: siThreads.path,
  tiktok: siTiktok.path,
  youtube: siYoutube.path,
  vimeo: siVimeo.path,
  telegram: siTelegram.path,
  whatsapp: siWhatsapp.path,
  messenger: siMessenger.path,
  signal: siSignal.path,
  line: siLine.path,
  viber: siViber.path,
  wechat: siWechat.path,
  linkedin: linkedinPath,
  github: siGithub.path,
  gitlab: siGitlab.path,
  stackoverflow: siStackoverflow.path,
  devto: siDevdotto.path,
  hashnode: siHashnode.path,
  producthunt: siProducthunt.path,
  notion: siNotion.path,
  discord: siDiscord.path,
  twitch: siTwitch.path,
  kick: siKick.path,
  rumble: siRumble.path,
  snapchat: siSnapchat.path,
  vk: siVk.path,
  mastodon: siMastodon.path,
  bluesky: siBluesky.path,
  reddit: siReddit.path,
  pinterest: siPinterest.path,
  spotify: siSpotify.path,
  soundcloud: siSoundcloud.path,
  applemusic: siApplemusic.path,
  applepodcasts: siApplepodcasts.path,
  bandcamp: siBandcamp.path,
  medium: siMedium.path,
  substack: siSubstack.path,
  goodreads: siGoodreads.path,
  dribbble: siDribbble.path,
  behance: siBehance.path,
  figma: siFigma.path,
  artstation: siArtstation.path,
  unsplash: siUnsplash.path,
  flickr: siFlickr.path,
  linktree: siLinktree.path,
  gmail: siGmail.path,
  shopify: siShopify.path,
  etsy: siEtsy.path,
  steam: siSteam.path,
  playstation: siPlaystation.path,
  roblox: siRoblox.path,
  googlemaps: siGooglemaps.path,
  googlecalendar: siGooglecalendar.path,
  calendly: siCalendly.path,
  paypal: siPaypal.path,
  patreon: siPatreon.path,
  buymeacoffee: siBuymeacoffee.path,
  kofi: siKofi.path,
  cashapp: siCashapp.path,
  venmo: siVenmo.path,
  stripe: siStripe.path,
  wise: siWise.path,
  revolut: siRevolut.path,
  bitcoin: siBitcoin.path,
  ethereum: siEthereum.path,
};

// Ordered list for the picker. `twitter` is an alias of `x`, so it's omitted
// here to avoid a duplicate cell.
export const iconOptions: string[] = [
  ...Object.keys(lucideIcons),
  ...Object.keys(brandIcons).filter((name) => name !== 'twitter'),
];

// Domain → icon. Matched by hostname suffix, so `open.spotify.com` and
// `spotify.com` both resolve to `spotify`. Order matters only for safety.
const DOMAIN_ICONS: Array<[string, string]> = [
  ['instagram.com', 'instagram'],
  ['facebook.com', 'facebook'],
  ['fb.com', 'facebook'],
  ['fb.me', 'facebook'],
  ['twitter.com', 'x'],
  ['x.com', 'x'],
  ['threads.net', 'threads'],
  ['tiktok.com', 'tiktok'],
  ['youtube.com', 'youtube'],
  ['youtu.be', 'youtube'],
  ['vimeo.com', 'vimeo'],
  ['t.me', 'telegram'],
  ['telegram.me', 'telegram'],
  ['wa.me', 'whatsapp'],
  ['whatsapp.com', 'whatsapp'],
  ['m.me', 'messenger'],
  ['messenger.com', 'messenger'],
  ['signal.me', 'signal'],
  ['line.me', 'line'],
  ['wechat.com', 'wechat'],
  ['linkedin.com', 'linkedin'],
  ['github.com', 'github'],
  ['gitlab.com', 'gitlab'],
  ['stackoverflow.com', 'stackoverflow'],
  ['dev.to', 'devto'],
  ['hashnode.com', 'hashnode'],
  ['producthunt.com', 'producthunt'],
  ['notion.so', 'notion'],
  ['notion.site', 'notion'],
  ['discord.gg', 'discord'],
  ['discord.com', 'discord'],
  ['twitch.tv', 'twitch'],
  ['kick.com', 'kick'],
  ['rumble.com', 'rumble'],
  ['snapchat.com', 'snapchat'],
  ['vk.com', 'vk'],
  ['mastodon.social', 'mastodon'],
  ['bsky.app', 'bluesky'],
  ['reddit.com', 'reddit'],
  ['pinterest.com', 'pinterest'],
  ['spotify.com', 'spotify'],
  ['soundcloud.com', 'soundcloud'],
  ['music.apple.com', 'applemusic'],
  ['podcasts.apple.com', 'applepodcasts'],
  ['bandcamp.com', 'bandcamp'],
  ['medium.com', 'medium'],
  ['substack.com', 'substack'],
  ['goodreads.com', 'goodreads'],
  ['dribbble.com', 'dribbble'],
  ['behance.net', 'behance'],
  ['figma.com', 'figma'],
  ['artstation.com', 'artstation'],
  ['unsplash.com', 'unsplash'],
  ['flickr.com', 'flickr'],
  ['linktr.ee', 'linktree'],
  ['etsy.com', 'etsy'],
  ['shopify.com', 'shopify'],
  ['steamcommunity.com', 'steam'],
  ['store.steampowered.com', 'steam'],
  ['roblox.com', 'roblox'],
  ['paypal.com', 'paypal'],
  ['paypal.me', 'paypal'],
  ['patreon.com', 'patreon'],
  ['buymeacoffee.com', 'buymeacoffee'],
  ['ko-fi.com', 'kofi'],
  ['cash.app', 'cashapp'],
  ['venmo.com', 'venmo'],
  ['stripe.com', 'stripe'],
  ['wise.com', 'wise'],
  ['revolut.me', 'revolut'],
  ['calendly.com', 'calendly'],
  ['maps.google.com', 'googlemaps'],
  ['goo.gl', 'googlemaps'],
  ['calendar.google.com', 'googlecalendar'],
];

// Auto-select an icon from a link URL by inspecting its domain/scheme. Returns
// null when nothing matches, so callers can leave the current icon untouched.
export function iconForUrl(raw: string): string | null {
  if (!raw) return null;
  const value = raw.trim().toLowerCase();
  if (value.includes('khqr') || value.includes('bakong')) return 'khqr';
  if (value.startsWith('mailto:')) return 'mail';
  if (value.startsWith('tel:')) return 'phone';

  let host: string;
  try {
    host = new URL(value.includes('://') ? value : `https://${value}`).hostname.replace(/^www\./, '');
  } catch {
    return null;
  }

  for (const [domain, icon] of DOMAIN_ICONS) {
    if (host === domain || host.endsWith(`.${domain}`)) return icon;
  }
  return null;
}

